# Generated by Django 5.0.7 on 2024-08-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('taxe', models.IntegerField()),
                ('order_cost', models.IntegerField()),
                ('order_cost_ttc', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('carrier_name', models.CharField(max_length=255)),
                ('carrier_price', models.IntegerField()),
                ('payment_method', models.CharField(max_length=255)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('solde_price', models.IntegerField()),
                ('regular_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('taxe', models.IntegerField()),
                ('sub_total_ht', models.IntegerField()),
                ('sub_total_ttc', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
    ]
